image: docker:git

services:
    - docker:dind

before_script:
    - apk add --no-cache make

stages:
    - lint
    - test
    - build

lint:
    stage: lint
    script:
        - make lint
test:
    stage: test
    script:
        - make test
build:
    stage: build
    script:
        - make build
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.bridge.systems:5005
        - docker build -t registry.bridge.systems:5005/ortb/reporter:$CI_BUILD_REF_NAME .
        - docker push registry.bridge.systems:5005/ortb/reporter:$CI_BUILD_REF_NAME
